name: Generate Changelog and README

on:
  push:
    branches:
      - main

jobs:
  generate_changelog_and_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install openai
        pip install gitpython

    # Run changelog generation script
    - name: Generate Changelog
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        GITHUB_EVENT_AFTER: ${{ github.event.after }}
      run: python .github/scripts/changelogAI.py

    # Run README generation script (nur wenn README noch nicht existiert)
    - name: Generate README if not exist
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GIT_AUTHOR_NAME: "github-actions[bot]"
        GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      run: python .github/scripts/readmeAI.py

    # Push changes to the repository
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md || echo "CHANGELOG.md not found or not changed"
        if git diff --staged --quiet; then
          echo "No changes to commit for CHANGELOG.md"
        else
          git commit -m "docs: update CHANGELOG via OpenRouter"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
        fi