name: Generate Changelog and README

on:
  push:
    branches:
      - main

jobs:
  generate_changelog_and_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install openai
        pip install gitpython

    # Run changelog generation script
    - name: Generate Changelog
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/scripts/changelogAI.py

    # Run README generation script (nur wenn README noch nicht existiert)
    - name: Generate README if not exist
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/scripts/readmeAI.py

    # Push changes to the repository
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md README.md
        git commit -m "docs: update README and CHANGELOG via OpenAI" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main